version: '3'

services:
  kasmvnc-proxy:
    image: firshme/kasmvnc-proxy:neo
    container_name: kasmvnc-proxy
    environment:
      - PROXY_PORT=28881
    ports:
      - "38881:38881"
    restart: unless-stopped
    networks:
      - base

networks:
  aisoc:
    driver: bridge
    name: base