version: '3'

services:
  kasmvnc-proxy:
    image: swr.cn-north-4.myhuaweicloud.com/firshme/kasmvnc-proxy:neo
    container_name: kasmvnc-proxy
    ports:
      - "38881:38881"
    environment:
      - TARGET_HOST=10.8.0.19
      - TARGET_PORT=33335
      - USERNAME=admin
      - PASSWORD=adminaisoc
      - PROXY_PORT=38881
      - ACCESS_TOKEN=adminaisoc
    restart: unless-stopped
    networks:
      - aisoc

networks:
  aisoc:
    driver: bridge
    name: aisoc